-- Storefront curated collections for /collections listing and detail pages.
-- Mirrors luxe-front src/domains/collections/lib/collections.config.ts slugs.
-- Run via: make seed-dev (or SEED_SQL_FILES=scripts/seed-storefront-collections.sql go run ./cmd/seed-sql)

INSERT INTO collections (
    slug,
    eyebrow,
    title,
    description,
    href,
    image_url,
    cta_label,
    sort_order,
    status,
    mode,
    collection_type,
    preview_sort,
    preview_is_new,
    rules_json,
    hero_title,
    hero_description,
    desktop_image_url,
    created_at,
    updated_at
) VALUES
    (
        'modern-essentials',
        'Spring edit',
        'Modern Essentials',
        'Refined staples built for everyday luxury — limited seasonal palette.',
        '/shop?sortBy=newest&showOnlyNew=true',
        'https://images.unsplash.com/photo-1483985988355-763728e6155d?w=1200&h=1400&fit=crop',
        'Shop the edit',
        0,
        'active',
        'dynamic',
        'smart',
        'newest',
        TRUE,
        '{"operator":"and","conditions":[{"field":"is_new","operator":"eq","value":true}]}'::jsonb,
        'Modern Essentials',
        'Refined staples built for everyday luxury — limited seasonal palette.',
        'https://images.unsplash.com/photo-1483985988355-763728e6155d?w=1200&h=1400&fit=crop',
        NOW(),
        NOW()
    ),
    (
        'the-atelier-collection',
        'Crafted to last',
        'The Atelier Collection',
        'Hand-finished pieces from independent makers worldwide.',
        '/shop?sortBy=rating',
        'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&h=1400&fit=crop',
        'Explore collection',
        1,
        'active',
        'dynamic',
        'smart',
        'rating_desc',
        NULL,
        '{}'::jsonb,
        'The Atelier Collection',
        'Hand-finished pieces from independent makers worldwide.',
        'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1200&h=1400&fit=crop',
        NOW(),
        NOW()
    ),
    (
        'archive-sale',
        'Limited time',
        'Archive Sale',
        'Past-season favorites at exceptional value while sizes last.',
        '/shop?showOnlySale=true',
        'https://images.unsplash.com/photo-1441984904996-e0b495a6de39?w=1200&h=1400&fit=crop',
        'Shop sale',
        2,
        'active',
        'dynamic',
        'smart',
        'price_asc',
        NULL,
        '{"operator":"and","conditions":[{"field":"on_sale","operator":"eq","value":true}]}'::jsonb,
        'Archive Sale',
        'Past-season favorites at exceptional value while sizes last.',
        'https://images.unsplash.com/photo-1441984904996-e0b495a6de39?w=1200&h=1400&fit=crop',
        NOW(),
        NOW()
    ),
    (
        'trending-now',
        'Most loved',
        'Trending Now',
        'What shoppers are adding to cart this week across the marketplace.',
        '/shop?sortBy=trending',
        'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=1200&h=1400&fit=crop',
        'See trending',
        3,
        'active',
        'dynamic',
        'smart',
        'reviews_desc',
        NULL,
        '{}'::jsonb,
        'Trending Now',
        'What shoppers are adding to cart this week across the marketplace.',
        'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=1200&h=1400&fit=crop',
        NOW(),
        NOW()
    )
ON CONFLICT (slug) DO UPDATE SET
    eyebrow = EXCLUDED.eyebrow,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    href = EXCLUDED.href,
    image_url = EXCLUDED.image_url,
    cta_label = EXCLUDED.cta_label,
    sort_order = EXCLUDED.sort_order,
    status = EXCLUDED.status,
    mode = EXCLUDED.mode,
    collection_type = EXCLUDED.collection_type,
    preview_sort = EXCLUDED.preview_sort,
    preview_is_new = EXCLUDED.preview_is_new,
    rules_json = EXCLUDED.rules_json,
    hero_title = EXCLUDED.hero_title,
    hero_description = EXCLUDED.hero_description,
    desktop_image_url = EXCLUDED.desktop_image_url,
    updated_at = NOW();

-- Align legacy home-page collections with storefront status filter (active, not published).
UPDATE collections
SET status = 'active', updated_at = NOW()
WHERE status = 'published';
