-- Merchandising demo collections: published, scheduled, and draft.
-- Run via: make seed-dev (or SEED_SQL_FILES=scripts/seed-merchandising-collections.sql go run ./cmd/seed-sql)

INSERT INTO collections (
    slug,
    eyebrow,
    title,
    subtitle,
    description,
    href,
    image_url,
    cta_label,
    sort_order,
    status,
    mode,
    collection_type,
    starts_at,
    ends_at,
    preview_sort,
    sort_key,
    theme,
    rules_json,
    hero_title,
    hero_description,
    desktop_image_url,
    seo_title,
    seo_description,
    is_indexable,
    overlay_opacity,
    created_at,
    updated_at
) VALUES
    (
        'summer-edit',
        'In season',
        'Summer Edit',
        'Sun-ready essentials',
        'Published dynamic collection for summer merchandising — new and in-stock products.',
        '/collections/summer-edit',
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=1400&fit=crop',
        'Shop summer',
        10,
        'active',
        'dynamic',
        'smart',
        NULL,
        NULL,
        'newest',
        'newest',
        'seasonal',
        '{"operator":"and","conditions":[{"field":"is_new","operator":"eq","value":true},{"field":"in_stock","operator":"eq","value":true}]}'::jsonb,
        'Summer Edit',
        'Sun-ready essentials curated for the season.',
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=1400&fit=crop',
        'Summer Edit | Luxe',
        'Shop the published summer collection.',
        TRUE,
        0.25,
        NOW(),
        NOW()
    ),
    (
        'winter-landing',
        'Coming soon',
        'Winter Landing',
        'Cold-weather drop',
        'Scheduled collection that goes live on starts_at — use admin schedule + hourly cron.',
        '/collections/winter-landing',
        'https://images.unsplash.com/photo-1483664852095-d6cc68712063?w=1200&h=1400&fit=crop',
        'Notify me',
        11,
        'scheduled',
        'dynamic',
        'smart',
        NOW() + INTERVAL '30 days',
        NOW() + INTERVAL '120 days',
        'newest',
        'newest',
        'seasonal',
        '{"operator":"and","conditions":[{"field":"in_stock","operator":"eq","value":true},{"field":"min_rating","operator":"gte","value":4}],"groups":[{"operator":"or","conditions":[{"field":"is_new","operator":"eq","value":true},{"field":"on_sale","operator":"eq","value":true}]}]}'::jsonb,
        'Winter Landing',
        'Cold-weather pieces — scheduled for the first day of the campaign window.',
        'https://images.unsplash.com/photo-1483664852095-d6cc68712063?w=1200&h=1400&fit=crop',
        'Winter Landing | Luxe',
        'Upcoming winter merchandising collection.',
        TRUE,
        0.3,
        NOW(),
        NOW()
    ),
    (
        'games-draft',
        'Internal',
        'Games Draft',
        'Work in progress',
        'Draft dynamic collection for games merchandising — hidden from storefront until published.',
        '/collections/games-draft',
        'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&h=1400&fit=crop',
        'Shop games',
        12,
        'draft',
        'dynamic',
        'smart',
        NULL,
        NULL,
        'rating_desc',
        'rating_desc',
        'editorial',
        '{"operator":"and","conditions":[{"field":"search","operator":"contains","value":"game"},{"field":"in_stock","operator":"eq","value":true}]}'::jsonb,
        'Games Draft',
        'Draft query for game-related catalog products.',
        'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&h=1400&fit=crop',
        'Games Draft | Luxe',
        'Draft games collection (admin only).',
        FALSE,
        0.25,
        NOW(),
        NOW()
    )
ON CONFLICT (slug) DO UPDATE SET
    eyebrow = EXCLUDED.eyebrow,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    description = EXCLUDED.description,
    href = EXCLUDED.href,
    image_url = EXCLUDED.image_url,
    cta_label = EXCLUDED.cta_label,
    sort_order = EXCLUDED.sort_order,
    status = EXCLUDED.status,
    mode = EXCLUDED.mode,
    collection_type = EXCLUDED.collection_type,
    starts_at = EXCLUDED.starts_at,
    ends_at = EXCLUDED.ends_at,
    preview_sort = EXCLUDED.preview_sort,
    sort_key = EXCLUDED.sort_key,
    theme = EXCLUDED.theme,
    rules_json = EXCLUDED.rules_json,
    hero_title = EXCLUDED.hero_title,
    hero_description = EXCLUDED.hero_description,
    desktop_image_url = EXCLUDED.desktop_image_url,
    seo_title = EXCLUDED.seo_title,
    seo_description = EXCLUDED.seo_description,
    is_indexable = EXCLUDED.is_indexable,
    overlay_opacity = EXCLUDED.overlay_opacity,
    updated_at = NOW();
